### ISSUE TITLE
API Keys能被外网访问到 没有问题吗？

### ISSUE THREAD

**Issue by Hardrain980** [Coxxs/status#7]
访问./js/config.js 能够看到站点所对应的API Keys
比如[http://status.cqp.cc/js/config.js](url)

不需要在http server的配置文件里限制对config.js的访问吗？

**Comment by Coxxs** [comment]
本程序没有后端部分，Api Key 本身就在客户端加载，由于使用只读的 Monitor-Specific API Keys，因此没有安全问题。
